#!/bin/bash
. ../scripts/get_dialog_id
. ../scripts/is_xdotool_present

myexe="select_class"

echo "Check if xdotool is installed"
if [ $(is_xdotool_present) -eq 0 ]
then
  echo "ERROR: xdotool not installed, type 'sudo apt-get install xdotool' to install it"
  exit 1
fi

echo "Check if executable is present"
if [ ! -e $myexe ]
then
  echo "Executable '"$myexe"' not found, run 'qmake' and 'make' in this folder to create it"
  exit 1
fi

echo "Applications before:"
xlsclients -l

echo "Starting the application"
./$myexe &
sleep 3

echo "Applications after:"
xlsclients -l


echo "Check if the dialog can be found"
id=`get_dialog_id $myexe`
if [ ! $id ] 
then 
  echo "Error: should detect window with name"$myexe
  exit 1
fi

echo "Pick mage"
xdotool windowactivate $id sleep 0.5 key alt+m sleep 0.5

echo "Applications when having selected Mage:"
xlsclients -l

echo "Find new dialog"
id_new=`get_dialog_id "You've picked: mage"`
if [ ! $id_new ] 
then 
  echo "Error: could not detect correct window"
  exit 1
fi

echo "Press OK"
xdotool windowactivate $id_new sleep 0.1 key alt+o
