sudo: require
language: cpp
compiler: gcc

install:
  - sudo apt-get install -qq xdotool
  - sudo apt-get install -qq wmctrl
  - sudo apt-get install -qq leafpad
  - sudo apt-get install -qq gedit
  - sudo apt-get install -qq wmaker

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - wmaker start 1
  - cd scripts; ./is_xdotool_present_test.sh; cd ..
  - cd scripts; ./is_wmctrl_present_test.sh; cd ..
  - cd scripts; ./close_first_dialog_with_name_test.sh; cd ..
  - cd minimal_project; qmake; make; ./minimal_project.sh; cd ..
  - leafpad &
  - gedit &
  - wmctrl -m
  - DISPLAY=:0; wmctrl -l
  - DISPLAY=:1; wmctrl -l
  - DISPLAY=:2; wmctrl -l
  - DISPLAY=:3; wmctrl -l