sudo: required

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24 +extension RANDR"

install:
  - sudo apt-get install -y leafpad
  - sudo apt-get install -y mousepad
  - sudo apt-get install -y gedit
  - sudo apt-get install -qq xdotool
  # wmctrl may be replaced by xlsclients later, as the latter has shown to work on Travis
  - sudo apt-get install -qq wmctrl 
  # cowsay
  - sudo apt-get install cowsay
  - export PATH=/usr/bin:/bin:/usr/games


before_script:
  - export DISPLAY=:99.0
  - sleep 3

script:
  # Jorn and Thijs work
  - export
  - leafpad "test.txt" &
  - sleep 3
  - xlsclients -l
  - xdotool type "test"
  - xdotool key ctrl+s
  - sleep 10
  - ls
  - cat test.txt
  - leafpad "onetwothree.txt" &
  - sleep 3
  - xdotool type "unosdostres"
  - xdotool key ctrl+s
  - sleep 1 
  - xdotool key alt+F10
  - sleep 1
  - xdotool mousemove 0 1023 click 3
  - sleep 10
  - ls
  - cat onetwothree.txt
  # Get some more windows, to see if xlsclients -l can distinguish those
  - leafpad "1.txt" &
  - leafpad "2.txt" &
  - mousepad &
  - leafpad &
  - xlsclients -l
  # Scripts
  - cd scripts
  - ./close_first_dialog_test
  - ./count_exes_test
  - ./cowsay_twice_test
  - ./get_dialog_id_test
  - ./get_height_of_first_dialog_test
  - ./get_width_of_first_dialog_test
  - ./get_x_of_first_dialog_test
  - ./get_y_of_first_dialog_test
  - ./is_dialog_present_test
  - ./is_leafpad_present_test
  - ./is_wmctrl_present_test
  - ./is_xdotool_present_test
  - ./set_mouse_at_close_glyph_of_first_dialog_test
  - cd ..
  # Minimal project
  - cd minimal_project
  - ./minimal_project_build
  - ./minimal_project_test_complete
  - ./minimal_project_test
  - cd ..
  # Select class
  - cd select_class
  - ./select_class_build
  - ./select_class_test_complete
  - ./select_class_test
  - cd ..
