sudo: require
language: cpp
compiler: gcc
env: DISPLAY=:99.0

install:
  - sudo apt-get install -qq xdotool
  - sudo apt-get install -qq wmctrl
  - sudo apt-get install -qq leafpad
  - sudo apt-get install -qq gedit


# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - travis token
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - cd scripts; ./is_xdotool_present_test.sh; cd ..
  - cd scripts; ./is_wmctrl_present_test.sh; cd ..
  - cd scripts; ./close_first_dialog_with_name_test.sh; cd ..
  - cd minimal_project; qmake; make; ./minimal_project_complete.sh; ./minimal_project.sh; cd ..
  - leafpad &
  - gedit &
  - wmctrl -m
  - DISPLAY=:0; wmctrl -l
  - DISPLAY=:1; wmctrl -l
  - DISPLAY=:99; wmctrl -l
  - DISPLAY=:99.0; wmctrl -l
