sudo: required
language: cpp
compiler: gcc

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24 +extension RANDR"

install:
  # xdotool
  - sudo apt-get install -qq xdotool
  - sudo apt-get install -qq leafpad

script:
  - leafpad "test.txt" &
  - sleep 3
  - xlsclients -l
  - xdotool type "test"
  - xdotool key ctrl+s
  - sleep 10
  - ls
  - cat test.txt
  - leafpad "onetwothree.txt" &
  - sleep 3
  - xdotool type "unosdostres"
  - xdotool key ctrl+s
  - sleep 1 
  - xdotool key alt+F10
  - sleep 1
  - xdotool mousemove 0 1023 click 3
  - sleep 10
  - ls
  - cat onetwothree.txt
  - cd scripts; ./is_xdotool_present_test.sh; cd ..
  - cd scripts; ./is_wmctrl_present_test.sh; cd ..
  - cd scripts; ./close_first_dialog_with_name_test.sh; cd ..
  - cd minimal_project; qmake; make; ./minimal_project_complete.sh; ./minimal_project.sh; cd ..
  - gedit "test1" &
  - gedit "test2" &
  - leafpad &
  - mousepad &
  - wmctrl -m
  - wmctrl -l
