#!/bin/bash

# Close the first window with the arguments
# as its window title
# Returns an error code. A zero denotes that everything went OK

. get_dialog_id_by_title

function close_first_dialog_by_title
{
  id=`get_dialog_id_by_title "$@"`
  if [ ! $id ] 
  then
    echo 1
  else
    xdotool windowactivate $id sleep 0.1 key alt+F4
    echo 0
  fi
}
