#!/bin/bash

. close_first_dialog
. get_x_of_first_dialog

exe_name="Leafpad"

leafpad &
sleep 1
dialog_x=`get_x_of_first_dialog $exe_name`

if [ -z $dialog_x  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found an x of "$dialog_x" of dialog with name '"$exe_name"'"
  close_first_dialog $exe_name > /dev/null
fi
