#!/bin/bash

. close_first_dialog
. get_y_of_first_dialog

exe_name="Leafpad"

leafpad &
sleep 1
dialog_y=`get_y_of_first_dialog $exe_name`

if [ -z $dialog_y  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found a y of "$dialog_y" of dialog with name '"$exe_name"'"
  close_first_dialog $exe_name > /dev/null
fi
