#!/bin/bash

# Get the ID of the *first* window with the arguments
# as the window class name

# This version can be used on Travis, use the Name of a window
# Works for mousepad on local computer:
#   Window 0x6400001:
#     Machine:  pc-157-104
#     Name:  Mousepad
#     Icon Name:  Mousepad
#     Command:  mousepad
#     Instance/Class:  mousepad/Mousepad
# Works for minimal_application on local computer:
#   Window 0x9e00001:
#     Machine:  pc-157-104
#     Name:  minimal_project
#     Icon Name:  minimal_project
#     Command:  minimal_project
#     Instance/Class:  minimal_project/Minimal_project
# Works for select_class on local computer:
#   Window 0x9e00001:
#     Machine:  pc-157-104
#     Name:  select_class
#     Icon Name:  select_class
#     Command:  select_class
#     Instance/Class:  select_class/Select_class
# Does work for leafpad on Travis:
#   Window 0x200001:
#     Machine:  testing-gce-a7d3bf48-2384-4ab5-80da-c31003907c32
#     Name:  Leafpad
#     Icon Name:  leafpad
#     Command:  leafpad
#     Instance/Class:  leafpad/Leafpad
# Does not work for minimal_application on Travis:
#   Window 0x800002:
#     Machine:  testing-gce-a7d3bf48-2384-4ab5-80da-c31003907c32
#     Name:  Dialog
#     Command:  ./minimal_project
#     Instance/Class:  minimal_project/Minimal_project
# Does not work for select_class on Travis:
#   Window 0xa00002:
#     Machine:  testing-gce-a7d3bf48-2384-4ab5-80da-c31003907c32
#     Name:  Select a class
#     Command:  ./select_class
#     Instance/Class:  select_class/Select_class
function get_dialog_id_by_name
{
  echo `xlsclients -l | egrep -i --before-context=2 "Name:.*$*" | egrep "Window" | cut -f 1 -d ":" | cut -f 2 -d " " | head -n 1`
}
