#!/bin/bash
. get_dialog_id_by_name
. get_dialog_id_by_title

function get_dialog_id
{
  id_by_name=`get_dialog_id_by_name .*$*`
  if [ $id_by_name ] 
  then 
    echo $id_by_name
  else
    id_by_title=`get_dialog_id_by_title .*$*`
    echo $id_by_title
  fi 
}