#!/bin/bash

# Get the ID of the *first* window with the arguments
# as the window title bar text
# Cannot be used on Travis
function get_dialog_id_by_title
{
  echo `wmctrl -l | egrep "$*" | head -n 1 | cut -f 1 -d ' '`
}
