#!/bin/bash

# Get the height of the first window with the arguments
# as its window title
# Shows nothing if the window cannot be found

. ../scripts/get_dialog_id

function get_height_of_first_dialog
{
  id=`get_dialog_id "$@"`
  if [ $id ] 
  then
    echo `xdotool getwindowgeometry $id | egrep "Geometry" | cut -d ':' -f 2 | cut -d 'x' -f 2`
  fi
}
