#!/bin/bash

. close_first_dialog
. get_width_of_first_dialog

exe_name="Leafpad"

leafpad &
sleep 3

dialog_width=`get_width_of_first_dialog $exe_name`

if [ -z $dialog_width  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found a width of "$dialog_width" of dialog with name '"$exe_name"'"
  close_first_dialog $exe_name > /dev/null
fi
