#!/bin/bash

. close_first_dialog_with_name
. get_y_of_first_dialog_with_name

window_name="(Untitled)"

leafpad &
sleep 1
dialog_y=`get_y_of_first_dialog_with_name $window_name`

if [ -z $dialog_y  ] 
then 
  echo "Error: could not find window with name "$window_name
  exit 1
else
  echo "OK: found a y of "$dialog_y" of dialog with name '"$window_name"'"
  close_first_dialog_with_name $window_name > /dev/null
fi
