#!/bin/bash
. get_dialog_id

# Checks if there is at least one dialog with the arguments of the application its name

function is_dialog_present
{
  id=`get_dialog_id $@`
  if [ -z $id ] 
  then
    echo 0
  else
    echo 1
  fi
}
