#!/bin/bash
. ../scripts/close_first_dialog
. ../scripts/count_exes
. ../scripts/get_dialog_id
. ../scripts/get_height_of_first_dialog
. ../scripts/get_width_of_first_dialog
. ../scripts/get_x_of_first_dialog
. ../scripts/get_y_of_first_dialog
. ../scripts/is_xdotool_present
. ../scripts/set_mouse_at_close_glyph_of_first_dialog


exe_name="minimal_project"

#################################
# Check if all needed is present
#################################

echo "Check if xdotool is installed"
if [ $(is_xdotool_present) -eq 0 ]
then
  echo "ERROR: xdotool not installed, type 'sudo apt-get install xdotool' to install it"
  exit 1
fi

echo "Check if executable is present"
if [ ! -e $exe_name ]
then
  echo "Executable '"$exe_name"' not found, run 'qmake' and 'make' in this folder to create it"
  exit 1
fi

###############################
# Counting applications
###############################

echo "Counting number of executables"
echo "Applications before:"
xlsclients -l
exes_before=`count_exes`
echo "exes_before: "$exes_before

###############################
# Starting the application
###############################
echo "Starting the application"
./$exe_name &
sleep 1

###############################
# Counting applications
###############################

echo "Applications after:"
xlsclients -l
exes_after=`count_exes`
echo "exes_after: "$exes_after

if [ $exes_before -eq $exes_after ] 
then
  echo "ERROR: just as much exes before and after starting the exe"
fi

###############################
# Check if application can be detected
###############################

echo "Check if the dialog can be found"
id=`get_dialog_id $exe_name`
if [ ! $id ] 
then 
  echo "Error: should detect window with name"$exe_name
  exit 1
fi

sleep 1

################
# Show geometry
################
dialog_x=`get_x_of_first_dialog $exe_name`

if [ -z $dialog_x  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found an x of "$dialog_x" of dialog with name '"$exe_name"'"
fi

sleep 1

dialog_y=`get_y_of_first_dialog $exe_name`

if [ -z $dialog_y  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found a y of "$dialog_y" of dialog with name '"$exe_name"'"
fi

sleep 1

dialog_width=`get_width_of_first_dialog $exe_name`

if [ -z $dialog_width  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found a width of "$dialog_width" of dialog with name '"$exe_name"'"
fi

sleep 1

dialog_height=`get_height_of_first_dialog $exe_name`

if [ -z $dialog_height  ] 
then 
  echo "Error: could not find window with name "$exe_name
  exit 1
else
  echo "OK: found a height of "$dialog_height" of dialog with name '"$exe_name"'"
fi

sleep 1

######################
# Closing window
######################

echo "Close the dialog using ALT-F4"
error=`close_first_dialog $exe_name`
if [ ! $error -eq 0 ]
then 
  echo "Error: could not close dialog with name "$exe_name
  exit 1
fi

sleep 1

echo "Check if the dialog is closed"
id=`get_dialog_id $exe_name`
if [ $id ] 
then 
  echo "Error: dialog should be closed"
  exit 1
fi
