#!/bin/bash
. ../scripts/close_first_dialog
. ../scripts/count_exes
. ../scripts/get_dialog_id
. ../scripts/is_xdotool_present
. ../scripts/set_mouse_at_close_glyph_of_first_dialog


myexe="minimal_project"

echo "Check if xdotool is installed"
if [ $(is_xdotool_present) -eq 0 ]
then
  echo "ERROR: xdotool not installed, type 'sudo apt-get install xdotool' to install it"
  exit 1
fi

echo "Check if executable is present"
if [ ! -e $myexe ]
then
  echo "Executable '"$myexe"' not found, run 'qmake' and 'make' in this folder to create it"
  exit 1
fi

echo "Counting number of executables"
echo "Applications before:"
xlsclients -l
exes_before=`count_exes`
echo "exes_before: "$exes_before

echo "Starting the application"
./$myexe &
sleep 1


echo "Applications after:"
xlsclients -l
exes_after=`count_exes`
echo "exes_after: "$exes_after

if [ $exes_before -eq $exes_after ] 
then
  echo "ERROR: just as much exes before and after starting the exe"
fi


echo "Check if the dialog can be found"
id=`get_dialog_id $myexe`
if [ ! $id ] 
then 
  echo "Error: should detect window with name"$myexe
  exit 1
fi

sleep 1

echo "Close the dialog using ALT-F4"
error=`close_first_dialog $myexe`
if [ ! $error -eq 0 ]
then 
  echo "Error: could not close dialog with name "$myexe
  exit 1
fi

sleep 1

echo "Check if the dialog is closed"
id=`get_dialog_id $myexe`
if [ $id ] 
then 
  echo "Error: dialog should be closed"
  exit 1
fi

# sleep 1

# echo "Starting the application again"
# ./$myexe &
# sleep 1

# echo "Close the dialog by setting the mouse at the closing glyph and clicking"
# set_mouse_at_close_glyph_of_first_dialog $myexe
# sleep 1 # For suspense

# Set the mouse at the closing glyph again (in case the user moved the mouse)
# set_mouse_at_close_glyph_of_first_dialog $myexe
# xdotool click 1

